apiVersion: v1
kind: Pod
metadata:
  name: python
  labels:
    app: python
spec: 
  containers:
  - image: adnansee/python3
    name: python
    ports:
    - containerPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: python
  labels: 
    name: python
    app: python
spec:
  selector:
    app: python
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
