FROM jupyter/all-spark-notebook

RUN pip install jupyter -U && pip install jupyterlab
RUN pip install s3contents
RUN pip install hybridcontents
RUN sed -i "s|c = get_config()|'' |g" /etc/jupyter/jupyter_notebook_config.py

EXPOSE 8888

CMD ["tail", "-f", "/dev/null"]

